name: Test

on:
  push:
    paths-ignore:
    - README.md
    - '**/*.md'

jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test
      run: echo testing
